version: 2.1
jobs:
  test:
    docker:
      - image: circleci/python:3.9-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: mkdir output
      - run: mkdir outdir
      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            python3 -m robot -d outdir tests
      - store_artifacts:
          path: output
          destination: output
      - store_artifacts:
          path: outdir
          destination: outdir
workflows:
    build:
        when:
          and:
            - equal: [ develop, << pipeline.git.branch >> ]
        jobs:
            - test